### ISSUE TITLE
Replace router with Slim-Router

### ISSUE THREAD

**Issue by tolik518** [tolik518/blog.returnnull.de#14]
The current router is very static and should be replaced with the router from the slim framework.

Similarly like in the [simple-webshop repo](https://github.com/tolik518/simple_webshop/blob/master/code/src/Router.php).

**Comment by pavelee** [comment]
Hey, I prepared some other possible solution -> #17 

Take a look! 🫣

**Comment by pavelee** [comment]
Should we close this one?

**Comment by tolik518** [comment]
> Should we close this one?

Definitely! I didn't realize that I haven't assigned the PR to the issue
(most probably because it doesn't work on mobile)
