### ISSUE TITLE
Enhancement: Handle Empty Blog State Gracefully

### ISSUE THREAD

**Issue by tolik518** [tolik518/blog.returnnull.de#2]
Currently, when visiting the website with no posts, the software throws a fatal error due to a TypeError in the `MySQLArticleLoader::getLastArticleID()` function. The error message is as follows:
```php
Fatal error: Uncaught TypeError: Returnnull\MySQLArticleLoader::getLastArticleID(): Return value must be of type int, null returned in /var/www/html/src/Database/MySQLArticleLoader.php:42 Stack trace: 
#0 /var/www/html/src/Database/MySQLArticleLoader.php(14): Returnnull\MySQLArticleLoader->getLastArticleID() 
#1 /var/www/html/src/Pages/ArticlePage.php(38): Returnnull\MySQLArticleLoader->get(999999) 
#2 /var/www/html/src/Application.php(18): Returnnull\ArticlePage->run() 
#3 /var/www/html/public/index.php(25): Returnnull\Application->run() 
#4 {main} thrown in /var/www/html/src/Database/MySQLArticleLoader.php on line 42
```

You can reproduce it by deleting everything from the `Articles`-table.

This issue needs to be addressed to improve the user experience. Instead of throwing an exception, the software should display a user-friendly message or placeholder content when there are no posts.

This task involves identifying the cause of the exception and implementing a more graceful handling of the empty blog state. Your contributions towards resolving this issue will enhance the usability of the blog software.

**Comment by pavelee** [comment]
is it still open to take?

**Comment by tolik518** [comment]
@pavelee yes, should I assign it to you?

**Comment by pavelee** [comment]
Yes, please. I will look into it

**Comment by pavelee** [comment]
I prepared proposal in #11 with messages and fallback

![Zrzut ekranu 2023-10-19 o 21 47 36](https://github.com/tolik518/blog.returnnull.de/assets/68032486/1211bf82-cd59-481d-a9b8-dc5020792f4c)
