### ISSUE TITLE
Implement Autofill for Author Field in Admin Panel

### ISSUE THREAD

**Issue by tolik518** [tolik518/blog.returnnull.de#3]
In the current version of the blog software, the admin panel allows users to write a blog entry but requires manual input for the author field each time. This can be a repetitive and unnecessary task, especially for single-author blogs or frequent contributors.

To enhance the user experience and streamline the blog posting process, we need to implement an autofill functionality for the author field. This feature should automatically populate the author field with the logged-in user's name or a default author name, reducing the need for manual input.

This task involves adding the autofill feature to the author field in the admin panel's blog entry form. 

Your contributions towards this issue will significantly improve the user experience in the admin panel, making blog posting more efficient and user-friendly. Let's work together to enhance the blog software!

**Comment by pavelee** [comment]
Is the issue still open to take?

**Comment by tolik518** [comment]
@pavelee It is, I assigned the issue to you :)

**Comment by pavelee** [comment]
I prepared proposal at #15
