### ISSUE TITLE
Create Contributing.md

### ISSUE THREAD

**Issue by yuvicc** [tolik518/blog.returnnull.de#8]
**This is a(n):**
- [ ] Update to an existing code
- [ ] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**
I would like to create a CONTRIBUTING.md file so that new comers can understand the basic principles to contribute to the repositories and other related information

**Comment by tolik518** [comment]
I don't see the added value in contrast to a Readme - could you elaborate the added value?

**Comment by yuvicc** [comment]
The added value of a CONTRIBUTING file over a README file is that it provides more specific and detailed information for people who want to contribute to the project. It can help to reduce the number of questions that contributors have, and it can also help to ensure that contributions are made in a way that is consistent with the project's standards.

Here are some specific benefits of having a CONTRIBUTING file:

- It can help to attract new contributors by providing clear and concise information on how to get started.
- It can help to reduce the number of questions that contributors have, which can save time for the project maintainers.
- It can help to ensure that contributions are made in a way that is consistent with the project's standards, which can improve the quality of the project overall.
- It can help to document the project's contribution process, which can be useful for new and experienced contributors alike.

**Comment by tolik518** [comment]
@i-am-yuvi I am disappointed you've used GPT to answer my question, thus I'm not convinced that you're suitable für this task.

**Comment by yuvicc** [comment]
Fine I used gpt to give you the answer, but is that a reason to reject the issue!?

**Comment by tolik518** [comment]
Because:
1. I don't see a reason for a `CONTRIBUTING.MD` as you haven't elaborated it to me
2. I don't have any reason to think that the file you'll commit will be handcrafted, instead of generated

So no hard feelings @i-am-yuvi

**Comment by yuvicc** [comment]
Okay no problem
